# 🚀 AI-Powered E-commerce Analytics Hub Docker Compose
# Professional deployment configuration

version: '3.8'

services:
  # Main dashboard application
  dashboard:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    container_name: ai-ecommerce-dashboard
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      # Mount data directory for easy updates
      - ./assets/data:/app/assets/data:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dashboard-network

  # Development service (with hot reload)
  dashboard-dev:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    container_name: ai-ecommerce-dashboard-dev
    ports:
      - "8502:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      # Mount source code for development
      - .:/app
      - ./assets/data:/app/assets/data:ro
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - dashboard-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: dashboard-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - dashboard
    restart: unless-stopped
    profiles:
      - production
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  dashboard-data:
    driver: local 